/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// Caffe2JobListerExpansion allows custom methods to be added to
// Caffe2JobLister.
type Caffe2JobListerExpansion interface{}

// Caffe2JobNamespaceListerExpansion allows custom methods to be added to
// Caffe2JobNamespaceLister.
type Caffe2JobNamespaceListerExpansion interface{}
